---
title: "The Capstone Begins"
author: "suttonbm"
date: 2016-06-16
author: suttonbm
layout: post
categories:
  - projects
tags:
  - coursera
  - data.science
  - R
project: datasciencecoursera.capstone
excerpt: >
  Today is the day I start the capstone project.
---

So today is the day I start the capstone project for the JHU Data Science specialization on Coursera.  First impressions?  I'm a little disappointed that everyone works on the same project.  I was anticipating that the capstone would be more self-guided and open-ended.  However, it seems like there's quite a bit of structure surrounding the project.  They leave it up to the student to figure out the technical bits, but not so much the scope.  I guess I understand why they chose to set up the program this way, but I'd much prefer to create a project from my imagination, or, expand upon my project from Developing Data Projects.

##### Side Note
My developing data products project is here:
[https://suttonbm.shinyapps.io/DDP_Final_Project/](https://suttonbm.shinyapps.io/DDP_Final_Project/)

I'm going to try and write about my experience working on the capstone as much as I can remember to.  Not that I expect anyone to actually look at this blog aside from me, but maybe someone out there will find this stuff useful at some point...